name: maintenance

on:
  # So that PRs touching the same files as the push are updated
  push:
  # So that the `dirtyLabel` is removed if conflicts are resolve
  # We recommend `pull_request_target` so that github secrets are available.
  # In `pull_request` we wouldn't be able to change labels of fork PRs
  pull_request_target:
    types: [synchronize]

jobs:
  main:
    runs-on: ubuntu-latest
    if: |
      !(github.event.name == 'pull_request_target')
    steps:
      - name: check if prs are dirty
        uses: eps1lon/actions-label-merge-conflict@releases/2.x
        with:
          dirtyLabel: "has conflicts"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
  conflicts-cleanup:
    name: Remove `has conflicts` label after conflict resolution
    runs-on: ubuntu-latest
    if: |
      (github.event.name == 'pull_request_target')
    steps:
      - name: Debug
        run: echo ${{github.event.head_commit.message}}
      - name: Remove "has conflicts" label
        uses: andymckay/labeler@master
        with:
          remove-labels: "has conflicts"
