name: maintenance

on:
  # So that PRs touching the same files as the push are updated
  push:
  # So that the `dirtyLabel` is removed if conflicts are resolve
  # We recommend `pull_request_target` so that github secrets are available.
  # In `pull_request` we wouldn't be able to change labels of fork PRs
  pull_request:
    types: [synchronize]

jobs:
  main:
    runs-on: ubuntu-latest
    if: |
      !(github.event_name == 'pull_request')
    steps:
      - name: debug
        run: echo ${{github.event_name}}
      - name: check if prs are dirty
        uses: eps1lon/actions-label-merge-conflict@releases/2.x
        with:
          dirtyLabel: "has conflicts"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
  conflicts-cleanup:
    name: Remove `has conflicts` label after conflict resolution
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'pull_request')
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Debug
        id: get-info
        run: |
          echo ${{github.event.head_commit.message}}
          echo ${{github.event_name}}
          echo ${{github.ref_name}}
          echo "message=$(git show -s --format=%s)" >> GITHUB_OUTPUT
      - run: echo ${{steps.get-info.outputs.message}}
      - name: Remove "has conflicts" label
        if: contains(steps.get-info.outputs.message, 'Merge branch ''main''')
        uses: andymckay/labeler@master
        with:
          remove-labels: "has conflicts"
