name: notify user

on:
  push:

jobs:
  notify-user:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          content=`cat .github/workflows/user-handlers.json`
          echo "$content"
          echo "handlers=`$content`" >> $GITHUB_OUTPUT
        id: read-handlers
      - name: "print user"
        run: |
          echo "Hello"
          echo "${{ steps.read-handlers.outputs.handlers }}"
# echo "{{ fromJson(steps.read-handlers.outputs.handlers).alvaromartmart.slack }}"
        

