name: notify user

on:
  push:

jobs:
  notify-user:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          slack_value=$(jq --arg user "alvaromartmart" '.[$user].slack' .github/workflows/user-handlers.json)
          echo $slack_value
          slack_value2=$(jq --arg user "alvaromartmart2" '.[$user].slack' .github/workflows/user-handlers.json)
          echo $slack_value2

# echo "{{ fromJson(steps.read-handlers.outputs.handlers).alvaromartmart.slack }}"
        

