name: notify user

on:
  push:

jobs:
  notify-user:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          content=`cat .github/workflows/user-handlers.json`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "handlers="$content"" >> $GITHUB_OUTPUT
        id: read-handlers
      - name: print user
        run: |
          echo "${{ steps.read-handlers.outputs.handlers }}"
          echo "${{ fromJson(steps.read-handlers.outputs.handlers).alvaromartmart.slack }}"
        

