
name: Release

on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
      - name: Release
        run: |
          gh release create beta2 -t beta2 --generate-notes -p
          
      