
name: Release

on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        run: |
          gh release create ${{github.sha}} --generate-notes -p
          
      