
name: Release

on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Release
        run: |
          gh release create ${{github.sha}} --generate-notes -p
          
      